In [38]:
import numpy as np

# numpy 1D and 2D array
a= np.array([1,2,3,4,5])
print(a)

b=np.array([[i for i in range(5)] for j in range(3)],dtype="int16")
print(b)


# shape of array
print(a.shape)
print(b.shape)

# dimension of array
print(a.ndim)
print(b.ndim)

# data type
print(a.dtype)
print(b.dtype)



[1 2 3 4 5]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
(5,)
(3, 5)
1
2
int32
int16


In [46]:
# some special array function
c= np.zeros([4,4],dtype='int32')
print(c)
print(c.dtype)

d= np.ones([3,3])
print(d)

e= np.full([2,2],4)
print(e)

iden = np.eye(4)
print(iden)

ran= np.random.random([4,4])
print(ran)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.85549005 0.5740077  0.32063742 0.72968362]
 [0.58909127 0.75649529 0.28327614 0.52922014]
 [0.78105681 0.66841074 0.67786919 0.77094131]
 [0.29622948 0.51234599 0.98549436 0.15655747]]


In [53]:
# by slicing we do not create new memory
b1=b[:2,1:3]
print(b1,b1.shape)

b2=b[1:2,:]
print(b2,b2.shape)

b3= b[1,:]
print(b3,b3.shape)

[[1 2]
 [1 2]] (2, 2)
[[0 1 2 3 4]] (1, 5)
[0 1 2 3 4] (5,)


In [66]:
# accessing in different ways
a1 = np.array([[1,2,4],[2,3,4],[4,4,4]])
print(a1[1,0])
print(a1[[0,1,2],[1,2,1]])

2
[2 4 4]


In [73]:
d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='int16')
e= np.array([0,2,0])

##print(d)
##print(e)

f=np.arange(3)
#print(f)
#print(e+f)
print(d)
d[e,f]+=10
#print(d[e,f])
print(d)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[11  2 13]
 [ 4  5  6]
 [ 7 18  9]
 [10 11 12]]


In [76]:
## boolean indexing
k=np.arange(4)
print(k)

bool_idx=(k>=1)
print(bool_idx)

[0 1 2 3]
[False  True  True  True]


In [87]:
## math matics on nupmy
x=np.array([[1,2,3],[4,5,6],[0,1,1]])
y=np.array([[2,3,3],[4,4,4],[3,3,3]])

# print(x+y)
# print(np.add(x,y))

# print(x-y)
# print(np.subtract(x,y))

# multiplication is elemnte wise
x1=np.array([[1,2],[3,5]])
y1=np.array([[1,2],[3,5]])
print(x1*y1)
print(np.dot(x1,y1))


[[ 1  4]
 [ 9 25]]
[[ 7 12]
 [18 31]]


In [92]:
# column wise summation
t=np.array([[1,2],[3,4],[1,1]])
print(t.sum())# prefix sum
print(t.sum(axis=0))## colum wise sum
print(t.sum(axis=1)) ## row wise sum


12
[5 7]
[3 7 2]


In [94]:
# transpose of matrix
t1=np.array([[1,2],[3,4]])
print(t1.T)

[[1 3]
 [2 4]]


In [105]:
#empty_like() function

t2=np.array([[1,2],[2,3],[4,5],[9,0]])
v1=[1,2]
z1=np.empty_like(t2)

# for i in range(4):
#     z1[i,:]=t2[i,:]+v1
# print(z1)

# print(t2+v1)

v2=np.array([[1,2],[3,4]])
v3=np.array([1,2])
print(v2+v3)## broadcasting

[[2 4]
 [4 6]]
